source("F:\\RPKUMAR\\Softwares\\Programs_R\\JD_Calculator\\mypackage\\dosJDCal.R")

source("F:\\RPKUMAR\\Softwares\\Programs_R\\JD_Calculator\\mypackage\\Stage_Case.R")

source("F:\\RPKUMAR\\Softwares\\Programs_R\\JD_Calculator\\mypackage\\Stage_1.R")
source("F:\\RPKUMAR\\Softwares\\Programs_R\\JD_Calculator\\mypackage\\Stage_2.R")
source("F:\\RPKUMAR\\Softwares\\Programs_R\\JD_Calculator\\mypackage\\Stage_3.R")
source("F:\\RPKUMAR\\Softwares\\Programs_R\\JD_Calculator\\mypackage\\Stage_4.R")
source("F:\\RPKUMAR\\Softwares\\Programs_R\\JD_Calculator\\mypackage\\Stage_5.R")
source("F:\\RPKUMAR\\Softwares\\Programs_R\\JD_Calculator\\mypackage\\Stage_6.R")
source("F:\\RPKUMAR\\Softwares\\Programs_R\\JD_Calculator\\mypackage\\Stage_7.R")
source("F:\\RPKUMAR\\Softwares\\Programs_R\\JD_Calculator\\mypackage\\Stage_8.R")
source("F:\\RPKUMAR\\Softwares\\Programs_R\\JD_Calculator\\mypackage\\Stage_9.R")
source("F:\\RPKUMAR\\Softwares\\Programs_R\\JD_Calculator\\mypackage\\Stage_10.R")
source("F:\\RPKUMAR\\Softwares\\Programs_R\\JD_Calculator\\mypackage\\Stage_11.R")
source("F:\\RPKUMAR\\Softwares\\Programs_R\\JD_Calculator\\mypackage\\Stage_12.R")

source("F:\\RPKUMAR\\Softwares\\Programs_R\\JD_Calculator\\mypackage\\calJD.R")

#library(devtools)
#library(roxygen2)
#package.skeleton("DCWCSol")
#DCWCSol <- as.package("DCWCSol")
#load_all()
#document()